### ISSUE TITLE
blocking wait until database ready

### ISSUE THREAD

**Issue by nicoulaj** [faokunega/pg-embed#5]
Currently the code uses a `sleep(start_timeout)`, maybe it would more reliable to replace it with calling [`pg_isready`](https://www.postgresql.org/docs/13/app-pg-isready.html) in a loop ?

**Comment by faokunega** [comment]
Hi, thanks for the suggestion. 
I will replace the `sleep(start_timeout)` with something more reliable. `pg_isready` would be the perfect candidate but the downloaded postgresql binaries are lightweight and don't contain `pg_isready`, so I think the best way is to use `libpq` and check the status with [PQping](https://www.postgresql.org/docs/current/libpq-connect.html). This on the other hand means `libpq` has to be installed on the system. This should be a reasonably easy to fulfill prerequisite that has to be met. If you think otherwise or have any objections please let me know. I'm planning on making an update that contains the changes this coming weekend.

**Comment by nicoulaj** [comment]
Actually I see you call `pg_ctl` with `--wait` option, which does just what we need according to [the docs](https://www.postgresql.org/docs/13/app-pg-ctl.html). So we can just await the `pg_ctl` process termination instead of spawning it in the background.

**Comment by faokunega** [comment]
Perfect solution, thanks for your input!
 I merged it, will publish it and make a version update.

**Comment by faokunega** [comment]
Version 0.5.0 has been published. I had some trouble piping the stdout for `pg_ctl start`, so I had to remove the `process_control` crate and replace it with the `tokio` timeout method.

**Comment by nicoulaj** [comment]
I tested it and it looks like it is working fine here, thank you!
